### ISSUE TITLE
not loading shipping options when editing edition

### ISSUE THREAD

**Issue by ckxpress** [likecoin/nft-book-press#107]
https://liker.land/zh-Hant/nft/class/likenft19ul7dkwj2p8fs3m6t4gy77p7mlgnyy3ehcmran2f4us8ctn6yw5sk7fx2z?ga_client_id=1430582497.1704286728&ga_session_id=1707708355&price_index=1

it's supposed to show 2 shipping options. 1 free, the other usd5. but it shows the default.

![Screenshot 2024-02-12 at 11 28 13 AM](https://github.com/likecoin/nft-book-press/assets/7088918/803c8af6-fb25-4b52-9aee-9eb06db4d53e)

**Comment by williamchong** [comment]
this ui should not appear, shipping option is defined in class level not edition level

**Comment by AuroraHuang22** [comment]
should be fixed on https://github.com/likecoin/nft-book-press/pull/88
