### ISSUE TITLE
unable to "Mark complete" a book

### ISSUE THREAD

**Issue by ckxpress** [likecoin/nft-book-press#169]
initially i thought it's the issue with session (which is another issue bothering me a lot), but i've tried many times and with different recipient and confirmed the issue.

https://www.loom.com/share/0dea881d89a746dea1585ae4b5831a70

**Comment by williamchong** [comment]
The issue was the api only allow setting claimed payment to `complete`, should allow all status except `complete`

**Comment by ckxpress** [comment]
when i mark complete 2 orders, my outstanding orders became -1 then -2.
<img width="167" alt="Screenshot 2024-08-14 at 15 30 24" src="https://github.com/user-attachments/assets/f27eaa7d-8c48-4e17-ae40-e85ae2855cfd">
<img width="180" alt="Screenshot 2024-08-14 at 15 31 24" src="https://github.com/user-attachments/assets/b3fe9b2d-e71e-43e6-8ff4-638f4cfe0e86">
