### ISSUE TITLE
provide QR at the same time as providing purchase link

### ISSUE THREAD

**Issue by ckxpress** [likecoin/nft-book-press#22]
when a purchase link of a particular channel or price index is generate, generate a QR code for user to download, in conjunction with copying the purchase link.

the filename of the QR code can be: purchase_booktitle_channelid_priceindex.jpg

**Comment by williamchong** [comment]
qrcode: https://github.com/likecoin/nft-book-press/pull/23
TODO: filename formatting

**Comment by ckxpress** [comment]
if the fix is deployed, then it's not fixed.

what i did just now:
* manage likenft19symzw3xmh42gukzts858wf6rsdkn6e4jtc9wp8jh4kphfmffy5s6acyxg
* change channel id to `mountzero`
* download png -> correct
* change price index to `1`
* download png -> wrong: https://api.like.co/likernft/book/purchase/likenft19symzw3xmh42gukzts858wf6rsdkn6e4jtc9wp8jh4kphfmffy5s6acyxg/new?from=mountzero&price_index=0 (same as above). but the qr displayed on screen is correct

**Comment by williamchong** [comment]
Seems issue of underlying qrcode library, qr code does not update after you have downloaded once for png/jpg

**Comment by williamchong** [comment]
Much easier to debug once  you have reproducible steps
https://github.com/likecoin/nft-book-press/pull/28 Should fix this
