### ISSUE TITLE
Gift book feature not reading CSV

### ISSUE THREAD

**Issue by ckxpress** [likecoin/nft-book-press#259]
* i input all the fields
* with the downloaded template, made a csv with 1 record (attached)
[gift_list.csv](https://github.com/user-attachments/files/18271871/gift_list.csv)
* the system doesn't read the csv
* and can't tap "confirm"
<img width="1189" alt="Screenshot 2024-12-30 at 11 47 25" src="https://github.com/user-attachments/assets/e58c8e65-3cd0-4466-b998-7938a33dbf3a" />

**Comment by ckxpress** [comment]
p.s. i have already gifted the reader by directly sending to him

**Comment by williamchong** [comment]
cause: https://github.com/nuxt/ui/issues/1569
